### ISSUE TITLE
Show delta of changes between reports

### ISSUE THREAD

**Issue by naliwajek** [netguru/perfguru#1]
App should show not only current values but also delta values - the difference between current and last report so that with one glance I can see is my app doing better or worse than the last week.

Right now only the current values are shown: http://screencast.com/t/bIubAP5suTX

(I hope SO much for this repo to be the app I'm talking about xD)

**Comment by mic-kul** [comment]
:+1:

**Comment by naliwajek** [comment]
Might be useful by they way:
▲ - U+25B2 BLACK UP-POINTING TRIANGLE
▼ - U+25BC BLACK DOWN-POINTING TRIANGLE

:cat:
